import './globals.css'
import Link from 'next/link'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const CustomLink = ({href, children})=>{
  return <Link href={href} prefetch={false}>{children}</Link>
}


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className='container mx-auto text-center  '>
          <ul className='flex gap-4 py-4 '>
            <li>
              <CustomLink href="/">Home Page</CustomLink>
            </li>
            <li className='flex flex-col justify-start bg-slate-200 p-2'>
              <CustomLink href="/ssr">SSR Page</CustomLink>
              <CustomLink href="/heavy/ssr">SSR Page Heavy</CustomLink>
              <CustomLink href="/heavy-suspense/ssr">SSR Page Heavy (suspense)</CustomLink>
              <CustomLink href="/heavy-dynamic-import/ssr">SSR Page Heavy (dynamic import)</CustomLink>
            </li>
            <li className='flex flex-col justify-start bg-slate-200 p-2'>
              <CustomLink href="/isr">ISR Page</CustomLink>
              <CustomLink href="/heavy/isr">ISR Page Heavy</CustomLink>
              <CustomLink href="/heavy-suspense/isr">ISR Page Heavy (suspense)</CustomLink>
              <CustomLink href="/heavy-dynamic-import/isr">ISR Page Heavy (dynamic import)</CustomLink>
            </li>
            <li className='flex flex-col justify-start bg-slate-200 p-2'>
              <CustomLink href="/csr">CSR Page</CustomLink>
              <CustomLink href="/heavy/csr">CSR Page Heavy</CustomLink>
              <CustomLink href="/heavy-suspense/csr">CSR Page Heavy (suspense)</CustomLink>
              <CustomLink href="/heavy-dynamic-import/csr">CSR Page Heavy (dynamic import)</CustomLink>
            </li>
          </ul>
          <div className='flex  items-center justify-center'>
          {children}
          </div>
        </div>
      </body>
    </html>
  )
}
